# ------------------------------------------------------------------------------
#  Copyright Christopher Kormanyos 2022 - 2024.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)
# ------------------------------------------------------------------------------

name: xxd_codecov
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  gnumake-gcc-gcov-native:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        standard: [ c++14 ]
        compiler: [ g++ ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo apt install lcov dos2unix
      - name: gnumake-gcc-gcov-native
        run: |
          cd .gcov/make
          echo "build and run gcov/lcov/genhtml"
          echo "make prepare -f make_gcov_01_generic.gmk MY_ALL_COV=0 MY_CC=${{ matrix.compiler }} MY_STD=${{ matrix.standard }}"
          echo
          make prepare -f make_gcov_01_generic.gmk MY_ALL_COV=0 MY_CC=${{ matrix.compiler }} MY_STD=${{ matrix.standard }}
          echo
          echo "make gcov -f make_gcov_01_generic.gmk --jobs=8 MY_ALL_COV=0 MY_CC=${{ matrix.compiler }} MY_STD=${{ matrix.standard }}"
          echo
          make gcov -f make_gcov_01_generic.gmk --jobs=8 MY_ALL_COV=0 MY_CC=${{ matrix.compiler }} MY_STD=${{ matrix.standard }}
          echo
          echo "bash ./xxd_tests.sh"
          bash ./xxd_tests.sh
          echo
          echo "bash ./xxd_edges.sh"
          bash ./xxd_edges.sh
          echo
          echo "return to xxd root directory"
          cd ../..
      - name: upload-codecov
        uses: codecov/codecov-action@v4
        with:
          plugin: gcov
          file: ${{ runner.workspace }}/xxd/.gcov/make/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: false
